### ISSUE TITLE
API design

### ISSUE THREAD

**Issue by leifdenby** [cloudsci/cloudmetrics#33]
To start working out a common api for `cloudmetrics` I'm going to list all the metrics and the inputs each requires. An input is either a primary input (the `cloud_mask` or `cloud_scalar` field that a user has) or a derived input (a field that is derived from the primary input, but is the actual input required by any metric):

mask-based:
- `cloud_fraction` (previously `cf`)
   - `cloud_mask`
- `fractal_dimension` (previously `fracDim`)
   - `cloud_mask`
- `open_sky`
   - `cloud_mask`
- `orientation`
   - `cloud_mask`

object-based:
- `cop`
  - Primary: `cloud_mask` 
  - Derived: `labelled_image` -> `region_properties`
- `csd`
  - Primary: `cloud_mask` 
  - Derived: `labelled_image` -> `region_properties`
- `iorg`
   - Primary: `cloud_mask`
   - Derived: `labelled_image` -> `region_properties`
- `iorg_poisson`
   - Primary: `cloud_mask`
   - Derived: `labelled_image` -> `region_properties`
- `objects`
   - Primary: `cloud_mask`
   - Derived: `labelled_image` -> `region_properties`
- `rdf`
   - Primary: `cloud_mask`
   - Derived: `labelled_image` -> `region_properties`
- `scai`
   - Primary: `cloud_mask`
   - Derived: `labelled_image` -> `region_properties`

scalar-based:
- `cth`
  - `cloud_top_height` scalar field
- `cwp`
  - `cloud_water_path` scalar field
- `fourier`
   - Primary: Any `cloud_scalar` or `cloud_mask` would work (I've used `cloud_water_path` so far)
   - Derived: Radially and azimuthally averaged power spectra of the primary input
- `woi`
   - Primary: `cloud_scalar`
   - Derived: Scale-decomposed stationary wavelet spectra (in vertical, horizontal and diagonal directions)

other:
- `network` 
   - Will defer incorporating network metrics until we know a little more about what they're good at.

Please update/change these were there's things missing/wrong

Related to discussion on https://github.com/cloudsci/cloudmetrics/issues/28

**Comment by martinjanssens** [comment]
This is a great idea, I should have probably written this all out for you at the very outset. I've tried to be as comprehensive as I can, and have distinguished between metrics that can just be computed directly on a `cloud_scalar` or `cloud_mask` and metrics that can only be computed once a derived quantity has first been computed.

**Comment by martinjanssens** [comment]
The metrics that rely on these derived quantities are the ones we need to decide on how to handle I think. I really like what you did with the object metrics, where all object metrics can access a single, cached `labelled_image` and its `region_properties`. We could do something similar for the other two metric classes that rely on derived fields (`fourier` and `woi` currently, I think `network` metrics would work the same once we get to including those).

**Comment by martinjanssens** [comment]
The last thing to think about from me is that we could include all metrics that operate on `labelled_image`s and `region_properties` in the structure you've already written for https://github.com/cloudsci/cloudmetrics/pull/23, i.e. all those metrics that share the same primary and derived inputs (`cop`, `csd`, `iorg`, `iorgPoisson`, `rdf` and `scai`). I stuck a comment in that PR already to that effect  (https://github.com/cloudsci/cloudmetrics/pull/23#issuecomment-914078860), but I think this is probably the better place to discuss it.

**Comment by leifdenby** [comment]
> This is a great idea, I should have probably written this all out for you at the very outset. I've tried to be as comprehensive as I can, and have distinguished between metrics that can just be computed directly on a `cloud_scalar` or `cloud_mask` and metrics that can only be computed once a derived quantity has first been computed.

Thank you for adding this information - this is great!

**Comment by leifdenby** [comment]
> * `cth`
>   
>   * `cloud_top_height` scalar field
> 
> * `cwp`
>   
>   * `cloud_water_path` scalar field

Am I right in thinking that these are actually the same computation? Maybe we need a generic way of calculating statistical properties (std, mean, etc) of a "cloud scalar" for each labelled object?

**Comment by leifdenby** [comment]
> The last thing to think about from me is that we could include all metrics that operate on `labelled_image`s and `region_properties` in the structure you've already written for #23, i.e. all those metrics that share the same primary and derived inputs (`cop`, `csd`, `iorg`, `iorgPoisson`, `rdf` and `scai`). I stuck a comment in that PR already to that effect ([#23 (comment)](https://github.com/cloudsci/cloudmetrics/pull/23#issuecomment-914078860)), but I think this is probably the better place to discuss it.

Yes, I completely agree that we should put all the object-based metrics together. I've tried to group the metrics above, does this look right?

**Comment by martinjanssens** [comment]
> > * `cth`
> >   
> >   * `cloud_top_height` scalar field
> > * `cwp`
> >   
> >   * `cloud_water_path` scalar field
> 
> Am I right in thinking that these are actually the same computation just operating on different "cloud scalars"? Maybe we need a generic way of calculating statistical properties (std, mean, etc) of a "cloud scalar" for each labelled object?

Spot on, I was thinking the same thing! The `cloud_scalar` statistical properties could just operate directly on the field. In practice, you might want different statistics for different scalars, e.g. you might want to get the average `cloud_water_path` over the entire domain, while it makes most sense to average `cloud_top_height` only over the cloudy pixels. As a first suggestion, we could do:

- `scene_average(cloud_scalar)`
- `scene_std(cloud_scalar)`
- `cloud_average(cloud_scalar)`
- `cloud_std(cloud_scalar)`

Please just update if you think we need other statistics, different naming or different structure!

**Comment by martinjanssens** [comment]
> > The last thing to think about from me is that we could include all metrics that operate on `labelled_image`s and `region_properties` in the structure you've already written for #23, i.e. all those metrics that share the same primary and derived inputs (`cop`, `csd`, `iorg`, `iorgPoisson`, `rdf` and `scai`). I stuck a comment in that PR already to that effect ([#23 (comment)](https://github.com/cloudsci/cloudmetrics/pull/23#issuecomment-914078860)), but I think this is probably the better place to discuss it.
> 
> Yes, I completely agree that we should put all the object-based metrics together. I've tried to group the metrics above, does this look right?

Absolutely. What is the best way to put these together do you think? We could keep adding functions to the`cloudmetrics/objects/metrics.py` and `cloudmetrics/metrics/objects.py` files you've made for https://github.com/cloudsci/cloudmetrics/pull/23, but maybe that's too messy?

**Comment by leifdenby** [comment]
> Absolutely. What is the best way to put these together do you think? We could keep adding functions to the`cloudmetrics/objects/metrics.py` and `cloudmetrics/metrics/objects.py` files you've made for #23, but maybe that's too messy?

Yes, I think having individual files for the individual object-metrics would be good. I.e. we'll have `cloudmetrics/objects/rdf.py`, `cloudmetrics/objects/csd.py`, etc. I should then split out the metrics related to object geometry in `cloudmetrics/objects/geometry.py` I think.

**Comment by martinjanssens** [comment]
That sounds fantastic! Are you happy to make that split as a part of https://github.com/cloudsci/cloudmetrics/pull/23 and merge that one, since it introduces the necessary folder structure? I can definitely help refactoring the individual metrics.

**Comment by leifdenby** [comment]
> That sounds fantastic! Are you happy to make that split as a part of #23 and merge that one, since it introduces the necessary folder structure? I can definitely help refactoring the individual metrics.

Yes, I'll do that. And thank you!

**Comment by leifdenby** [comment]
After a long silence I've finally gotten round to working on this again @martinjanssens :) Thanks for the fruitful discussion here. I've had a go at implementing what I thought was the best structure based on our discussion. You can see the result of it in the merge pull-request above. I'll close this issue for now and we can re-open or open a new one if we decide this needs more discussion.
