### ISSUE TITLE
Generalising metrics which operate on additional scalar fields

### ISSUE THREAD

**Issue by leifdenby** [cloudsci/cloudmetrics#34]
I thought it was best to branch off our discussion on refactoring the metrics which operate on scalar fields together with a cloud mask (https://github.com/cloudsci/cloudmetrics/issues/33#issuecomment-915165587)

The idea is to make a general interface for:

> > * `cth`
> >   
> >   * `cloud_top_height` scalar field
> > * `cwp`
> >   
> >   * `cloud_water_path` scalar field

@martinjanssens you suggested that:

> The `cloud_scalar` statistical properties could just operate directly on the field. In practice, you might want different statistics for different scalars, e.g. you might want to get the average `cloud_water_path` over the entire domain, while it makes most sense to average `cloud_top_height` only over the cloudy pixels. As a first suggestion, we could do:
>
> - `scene_average(cloud_scalar)`
> - `scene_std(cloud_scalar)`
> - `cloud_average(cloud_scalar)`
> - `cloud_std(cloud_scalar)`

**Comment by leifdenby** [comment]
Yes, I like your suggestion! Maybe we could something like:

```
da_lwp = ... # load the field
da_cloudmask = ... # construct cloud mask
da_lwp_cloud_mean = cloudmetrics.cloud_mean(cloud_scalar=da_lwp, cloud_mask=da_cloudmask)
da_lwp_perobj_mean = cloudmetrics.object_mean(cloud_scalar=da_lwp, cloud_mask=da_cloudmask, ...)
```
Does that make sense? `.object_mean(...)` would need to call the functions for computing the labelled objects, so there might be some extra kwargs too.

With this we could introduce metrics in cloudmetrics-pipeline for scalar fields with names like `{scalar_name}__scene__{op}`, e.g. `cloud_top_height__scene__avg` or `cloud_water_path__cloud__mean`. I think it using double underscore `__` as the separator here is helpful because it allow us to easily have fields or operators which contain (single) underscores in their name. [django](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#gt) adopts this kind of convention and I use it a lot.

**Comment by martinjanssens** [comment]
That sounds great to me. I like the ability to compute basic statistics of any scalar property on a per-cloud basis too (e.g. the `per_obj_mean`). Would the intention of having a `cloud_mask=da_cloudmask` argument in the `*_mean` functions be to select whether to average over the `cloud_mask` or the entire scene? Anyway, I'm in favour of all you suggest here. Are we ready to open a PR for refactoring the scalar metrics in `cloudmetrics`?

**Comment by leifdenby** [comment]
>  I like the ability to compute basic statistics of any scalar property on a per-cloud basis too (e.g. the `per_obj_mean`). 

Yes, rereading what you wrote previously I'm realising that might not actually be what you meant by `cloud_mean(...)` :) Are you thinking that `cloud_mean(...)` and `scene_mean(...)` effectively do the following:

```python
def scene_mean(scalar):
   return np.mean(scalar)

def cloud_mean(scalar, cloud_mask):
   return np.mean(scalar[cloud_mask])
```

?

In that case we might not even need these. Option 1 seems simpler to me: 

```python
da_lwp = ... # load the field
da_cloudmask = ... # construct cloud mask

# option 1
lwp_mean = da_lwp.mean()
lwp_cloudmean = da_lwp.where(da_cloudmask).mean()

# option 2
lwp_mean = cloudmetrics.scene_mean(da_lwp)
lwp_cloudmean = cloudmetrics.cloud_mean(scalar=da_lwp, cloud_mask=da_cloudmask)
```

Or am I missing something? :)

**Comment by leifdenby** [comment]
> Yes, that's what I was thinking! I agree that Option 1 you suggest to deal with this works super well, at least for statistics that can be called directly as numpy functions. That does raise the broader question of whether it's not easier to do the same for any cloud scalar statistic? `cloud_scalar.mean()` is also shorter than `cloudmetrics.scene_mean(cloud_scalar)`, but there we'd do the second to make it easier to integrated in a pipeline, I think?
> 
> More broadly, I've had the feeling we might be overkilling a little with some of the simplest metrics, like `cloud_fraction`, where we're also giving the user a function that might take them less time to write themselves than to look up in our docs. I've not got strong feelings about it though, so I'm happy either way I think. :)

I agree. Ok, maybe what we should do is just remove `cth` and `cwp` and instead mention in the readme that we left these out since it is easier to just do them directly with the numpy primitives? I can also in cloudmetrics-pipeline add a convenience function for doing statistical aggregates on fields.

**Comment by martinjanssens** [comment]
I don't have too great of a perspective on what's easy and what's not in the pipeline, so I'm happy to defer to your expert judgement here: If you think statistical aggregates are easily added by the user, then I agree with removing `cth` and `cwp` from `cloudmetrics` and giving clear examples on how to compute statistical moments of `cloud_scalar` fields using numpy directly in the pipeline. :)

**Comment by leifdenby** [comment]
Great, that's what we do then :)

**Comment by leifdenby** [comment]
Following https://github.com/cloudsci/cloudmetrics/pull/39 the intention is that we will have function `cloudmetrics.scalar.mean(cloud_mask=..., scalar_field=...)` `cloudmetrics.scalar.kurtosis(cloud_mask=..., scalar_field=...)` etc

**Comment by leifdenby** [comment]
> Following #39 the intention is that we will have function `cloudmetrics.scalar.mean(cloud_mask=..., scalar_field=...)` `cloudmetrics.scalar.kurtosis(cloud_mask=..., scalar_field=...)` etc

I've made an attempt of this in https://github.com/cloudsci/cloudmetrics/pull/46

**Comment by leifdenby** [comment]
I'm closing this since #46 has now been merged and the reduction of per-object statistical reductions are going to be discussed in #48
