### ISSUE TITLE
Add notes about units to object-functions that return a length-scales

### ISSUE THREAD

**Issue by leifdenby** [cloudsci/cloudmetrics#49]
In https://github.com/cloudsci/cloudmetrics/issues/1#issuecomment-1026702797:

> * Maximum/mean length scale, mean perimeter: Currently calculated in pixels, can be made non-dimensional by dividing through domain characteristic size (e.g. `np.sqrt(mask.shape**2)`). If you know the resolution, you can then easily get these numbers in physical units by multiplying by the characteristic size and the resolution. We should probably document this.

**Comment by martinjanssens** [comment]
Nice, good to make an issue. of this. I can have a crack at it over the weekend if you like, @leifdenby.
