### ISSUE TITLE
releasing version v0.2.0

### ISSUE THREAD

**Issue by leifdenby** [cloudsci/cloudmetrics#50]
I think we're reaching a point where we could make `v0.2.0` quite soon with what we've got and what's nearly done. My feeling is that we can finish SCAI (https://github.com/cloudsci/cloudmetrics/pull/42), maybe RDF won't take to long (https://github.com/cloudsci/cloudmetrics/pull/43) either.

Here's my tentative list of things do TODO for v0.2.0

- [x] SCAI https://github.com/cloudsci/cloudmetrics/pull/42
    - changelog
-  <del>RDF https://github.com/cloudsci/cloudmetrics/pull/43 </del> - moved to `v0.3.0`
    - needs refactoring and need to define and implement a test 
- [x] naming conventions https://github.com/cloudsci/cloudmetrics/issues/47
    - quick search-replace throughout codebase
- [x] notes on units for length-scale metrics https://github.com/cloudsci/cloudmetrics/issues/49
   - extra documentation needs to be added to functions that return length-scales
- [x] refactoring Iorg to work on `object_labels` rather than `mask` https://github.com/cloudsci/cloudmetrics/issues/52
   - simple refactor to generalise i_org calculation

Does that sound ok @martinjanssens or have I missed something obvious?

**Comment by martinjanssens** [comment]
I agree, this is very exciting. That would be a release where all the metrics are refactored and could be computed using the package, in a more-or-less consistent way. 

I think we also still have to refactor the code that I wrote to compute `iorg` in the traditional manner (that was called `iorgPoisson`); we should probably refactor that also as part of this release? In fact, we could put it under the same umbrella as our current iorg function (if we need to refactor that to work on `object_labels` anyway), and have an optional keyword that points to the traditional version of the metric, or that which accounts for object size?

I would also like to add simple analysis routines at some point (e.g. reintroduce the PCA framework I used in the paper), but that could either be done in the pipeline repo or in a later release.

**Comment by leifdenby** [comment]
As I mentioned in my email @martinjanssens I suggest we push the refactoring of RDF to the next version (`v0.3.0`) so that we can get this release out there and people can start using it. Let me know if that sound ok to you or not :)

**Comment by martinjanssens** [comment]
Agreed!

**Comment by martinjanssens** [comment]
One thing that has been crossing my mind since I've been going over the docstrings to all the functions for #51, is whether we'd want to build a documentation as part of this release. The function docstrings should in principle be ready for this. I think you started on something like this in #37, @leifdenby, but I don't have the immediate overview over how far that's away from being integrated, and consequently if we should postpone it to a later release.

**Comment by leifdenby** [comment]
> One thing that has been crossing my mind since I've been going over the docstrings to all the functions for #51, is whether we'd want to build a documentation as part of this release. The function docstrings should in principle be ready for this. I think you started on something like this in #37, @leifdenby, but I don't have the immediate overview over how far that's away from being integrated, and consequently if we should postpone it to a later release.

I've created a new issue #63 to ensure that we don't forget about automatic documentation. To get ready for release v0.2.0 I've created a pull-request #62 - could you have a quick look if the changes I'm making are ok with you?

**Comment by leifdenby** [comment]
I'm closing this @martinjanssens since the first tagged version **is now live on pypi** :partying_face: :rocket: :star2:

After asking kindly the previous owner of the now-no-longer-used `cloudmetrics` package on pypi gave the package name to me, so we now have `cloudmetrics` on pypi and can do `pip install cloudmetrics` :smile:
