### ISSUE TITLE
Releasing v0.3.0

### ISSUE THREAD

**Issue by martinjanssens** [cloudsci/cloudmetrics#75]
Continuing the discussion started in #70 to release v0.3.0. We might debate whether we want to include still:

- @observingClouds 's performance-enhanced implementation of `open_sky` using `numba`
- @leifdenby 's work on better documentation

I'd be in favour of including both, unless they are longer-term projects for the two of you. If so, I'm happy to release what we have now.

**Comment by observingClouds** [comment]
Hi @martinjanssens,
I will need some time to do the implementation so please do not wait for my PR.

**Comment by observingClouds** [comment]
> Hi @martinjanssens,
> I will need some time to do the implementation so please do not wait for my PR.

I correct myself. It is done now. Refactoring the function was sufficient and numba did not help to improve the performance.

**Comment by leifdenby** [comment]
All done 😄 🥳  https://pypi.org/project/cloudmetrics/
